backend:
  name: git-gateway
  branch: panic-master

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: "Background Image", name: "background_image", widget: image}
          - {label: Logo, name: logo, widget: image}
          - {label: "Heading", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Artist", name: "artist", widget: object, fields: [{label: "Artist Name", name: name, widget: string}, {label: Image, name: image, widget: image}, {label: Description, name: description, widget: string}, {label: Website, name: website, widget: string}, {label: Tickets, name: tickets, widget: string} ,{label: Spotify, name: spotify, widget: string}]}
          - {label: Food, name: food, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
      - file: "src/pages/about.md"
        label: "About Page"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Background Image", name: "background_image", widget: image}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Community", name: "community", widget: object, fields: [{label: Title, name: title, widget: string, default: Community}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Text, name: text, widget: text}]}]}
          - {label: "Culture", name: "culture", widget: object, fields: [{label: Title, name: title, widget: string, default: Culture}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Text, name: text, widget: text}]}]}
          - {label: "Craft", name: "craft", widget: object, fields: [{label: Title, name: title, widget: string, default: Craft}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Text, name: text, widget: text}]}]}
         
      - file: "src/pages/calendar.md"
        label: "Calendar Page"
        name: "calendar"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "calendar-page"}
          - {label: "Background Image", name: "background_image", widget: image}
          - {label: "Page Title", name: "title", widget: "string"}
      - file: "src/pages/foodpage.md"
        label: "Food & Drink Page"
        name: "foodpage"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "foodpage"}
          - {label: "Page Title", name: "title", widget: "string"}
          - {label: "PDF Title", name: "pdf_title", widget: "string"}
          - {label: "PDF Filename (without .pdf)", name: "pdf_filename", widget: "string"}
          - label: "Menu"
            name: "menu"
            widget: "file"
            default: "/static/pdf/menu.pdf"
            media_library:
              config:
                multiple: true
      - file: "src/pages/community.md"
        label: "Community Page"
        name: "community"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "community-page"}
          - {label: "Background Image", name: "background_image", widget: image}
          - {label: "Page Title", name: "title", widget: "string"}
          - {label: "PDF Title", name: "pdf_title", widget: "string"}
          - {label: "PDF Filename (without .pdf)", name: "pdf_filename", widget: "string"}
          - label: "Flyer"
            name: "menu"
            widget: "file"
            default: "/static/img/sample.pdf"
            media_library:
              config:
                multiple: true
          - {label: "Section Title", name: "section_title", widget: "string"}
          - label: Gallery,
            name: gallery,
            widget: object,
            fields:
              label: Images
              name: images
              widget: list
              fields:
                label: Image
                name: image
                widget: image
                default: "/static/img/placeholder.jpg"
                media_library:
                  config:
                    multiple: true