backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: "Title Image", name: "image", widget: image}
          - {label: "Upcoming Events Section Title", name: "events_button_title", widget: "string"}
          - {label: "Heading", name: "title", widget: "string"}
          - {label: "Heading Description", name: "description", widget: "text"}
          - {label: "Artist Section Title", name: "artist_spotlight", widget: "string"}
          - {label: "Artist Image", name: "artist_image", widget: image}          
          - {label: "Artist Name", name: "artist_name", widget: "string"}
          - {label: "Artist Description", name: "artist_description", widget: "string"}
          - {label: "Playlist", name: "spotify_playlist", widget: "string"}
          - {label: "Food Section Title", name: "food_and_drinks_title", widget: "string"}
          - {label: "Food Section Description", name: "food_and_drinks_description", widget: "text"}
      - file: "src/pages/about.md"
        label: "About Page"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "about_title", name: "about_title", widget: "string"}
          - {label: "title", name: "title", widget: "string"}
          - {label: "description", name: "description", widget: "text"}
          - {label: "community_title", name: "community_title", widget: "string"}
          - {label: "community_description_p1", name: "community_description_p1", widget: "text"}
          - {label: "community_description_p2", name: "community_description_p2", widget: "text"}
          - {label: "community_description_p3", name: "community_description_p3", widget: "text"}
          - {label: "culture_title", name: "culture_title", widget: "string"}
          - {label: "culture_description_p1", name: "culture_description_p1", widget: "text"}
          - {label: "culture_description_p2", name: "culture_description_p2", widget: "text"}
          - {label: "craft_title", name: "craft_title", widget: "string"}
          - {label: "craft_description_p1", name: "craft_description_p1", widget: "text"}
          - {label: "craft_description_p2", name: "craft_description_p2", widget: "text"}
          - {label: "craft_description_p3", name: "craft_description_p3", widget: "text"}
      - file: "src/pages/calendar.md"
        label: "Calendar Page"
        name: "calendar"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "calendar-page"}
          - {label: "title", name: "title", widget: "string"}
      - file: "src/pages/foodanddrink.md"
        label: "Food & Drink Page"
        name: "foodpage"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "foodpage"}